maria:
  pv:
    - Name: mariadb
      Size: 8Gi
      Path: /data/db/
      PersistentVolumeReclaimPolicy: Retain

  pvc:
    - Name: data
      Size: 8Gi
      VolumeName: mariadb

  app: mariadb

  connexion:
    rootPassword:
    user:
    password: asecret
    database: logs

  image: 
    repository: mariadb:10
    pullPolicy: Always
    tag: mariadb

  volumeMount:
    name: data
    mountPath: /var/lib/mysql

  volume:
    name: data
    clainName: data

  service:
    name: maria-db
  
deno:
  pv:
    - Name: deno-server
      Size: 3Gi
      Path: /data/deno-server/
      PersistentVolumeReclaimPolicy: Retain

  pvc:
    - Name: logs
      Size: 1Gi
      VolumeName: deno-server

  volumeMount:
    name: logs
    mountPath: /srv/app/pvc

  volume:
    name: logs
    claimName: logs
  
  service:
    type: NodePort
    port: 8080
    name: deno-webserver

  image:
    repository: codebuds/deno-webserver:1.3.1
    pullPlicy: Always
    tag:

  replicaCount: 3