apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.maria.app }}
  name: {{ .Values.maria.app }}
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.maria.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.maria.app }}
    spec:
      containers:
      - image: {{ .Values.maria.image.repository }}
        imagePullPolicy: {{ .Values.maria.image.pullPolicy }}
        name: {{ .Values.maria.image.tag }}
        env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.maria.app }}-secret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.maria.app }}-secret
                  key: db
        volumeMounts:
                - mountPath: {{ .Values.maria.volumeMount.mountPath }}
                  name: {{ .Values.maria.volumeMount.name }}
      volumes:
                - name: {{ .Values.maria.volume.name }}
                  persistentVolumeClaim:
                      claimName: {{ .Values.maria.volume.clainName }}
