apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.maria.app }}-secret
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  password: {{ .Values.maria.connexion.password }}
  db: {{ .Values.maria.connexion.db }}