apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
data:
  user: {{ .Values.mariadb.auth.user }}
  password: {{ .Values.mariadb.auth.password }}
  database: {{ .Values.mariadb.auth.database }}
  rootPassword: {{ .Values.mariadb.auth.rootPassword }}