apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.maria.app }}
  name: {{ .Values.maria.service.name }}
  namespace: default
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: {{ .Values.maria.app}}
  type: LoadBalancer
