apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.servicemariadb.name }}
spec:
  ports:
    - port: {{ .Values.servicemariadb.port }}
  selector:
    app: {{ .Values.servicemariadb.name }}