apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Values.mariadb.pv.name }}
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.mariadb.pv.persistentVolumeReclaimPolicy }}
  storageClassName: standard
  capacity:
    storage: {{ .Values.mariadb.pv.size }}
  hostPath:
    path: {{ .Values.mariadb.pv.path }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.mariadb.pvc.name }}
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariadb.pvc.size }}
