apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-02-12T13:07:11Z"
    generation: 1
    labels:
        app: deno-webserver
    name: {{ .Release.Name }}-deno-webserver
    namespace: default
spec:
    progressDeadlineSeconds: 600
    replicas: {{ .Values.webserver.replicaCount }}
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: deno-webserver
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp:
            labels:
                app: deno-webserver
        spec:
            containers:
                -   image: {{ .Values.webserver.image.repository }}:{{ .Values.webserver.image.tag }}
                    imagePullPolicy: {{ .Values.webserver.image.pullPolicy }}
                    name: deno-webserver
                    resources: { }
                    env:
                        - name: MARIADB_HOST
                          value: {{ .Release.Name }}-maria-db

                    terminationMessagePath: /dev/termination-log
                    terminationMessagePolicy: File
                    volumeMounts:
                      - mountPath: {{ .Values.webserver.volumeMounts.mountPath }}
                        name: {{ .Release.Name }}-{{ .Values.webserver.volumeMounts.name }}
                    ports:
                      - name: http
                        containerPort: 8080
                        protocol: TCP
                    readinessProbe:
                        initialDelaySeconds: 20
                        periodSeconds: 60
                        httpGet:
                            path: /probe?probeType=readiness
                            port: http
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: { }
            terminationGracePeriodSeconds: 30
            volumes:
                - name: {{ .Release.Name }}-{{ .Values.webserver.volumes.name }}
                  persistentVolumeClaim:
                      claimName: {{ .Release.Name }}-{{ .Values.webserver.volumes.nameClaim }}