apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-02-12T13:07:11Z"
    generation: 1
    labels:
        app: deno-webserver
    name: {{ .Release.Name }}-deno-webserver
    namespace: default
spec:
    progressDeadlineSeconds: 600
    replicas: {{ .Values.webserver.replicaCount }}
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: deno-webserver
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp:
            labels:
                app: deno-webserver
        spec:
            securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                fsGroup: 1000
            initContainers:
                - name: check-mariadb
                  image: busybox:1.31
                  env:
                    - name: MARIADB_HOST
                      value: {{ .Release.Name }}-maria-db
                  command: [
                            'sh',
                            '-c',
                            "echo -e \"check mariadb\"; while ! nc -z $MARIADB_HOST 3306; do sleep 1; printf \"-\"; done; echo -e \" >> bdd ok \";"
                        ]
            ####### ne focntionne pas ...

            containers:
                -   image: {{ .Values.webserver.image.repository }}:{{ .Values.webserver.image.tag }}
                    imagePullPolicy: {{ .Values.webserver.image.pullPolicy }}
                    livenessProbe:
                        httpGet:
                            path: /prob?probeType=liveness
                            path: /prob
                            port: 80
                        initialDelaySeconds: 30
                        periodSeconds: 15
                    ###### 2eme methode si le httpGet ne focntionne pas 
                    # livenessProbe:
                    #     exec:
                    #         command:
                    #             - sh
                    #             - -c
                    #             - wget --spider localhost:8080
                    #     initialDelaySeconds: 30
                    #     periodSeconds: 15
                    resources:
                        requests:
                            memory: "10Mi"
                            cpu: "150m"
                        limits:
                            memory: "1Gi"
                            cpu: "500m"
                    name: deno-webserver
                    env:
                        - name: MARIADB_HOST
                          value: {{ .Release.Name }}-maria-db

                    terminationMessagePath: /dev/termination-log
                    terminationMessagePolicy: File
                    volumeMounts:
                      - mountPath: {{ .Values.webserver.volumeMounts.mountPath }}
                        name: {{ .Release.Name }}-{{ .Values.webserver.volumeMounts.name }}
                    ports:
                      - name: http
                        containerPort: 8080
                        protocol: TCP
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: { }
            terminationGracePeriodSeconds: 30
            volumes:
                - name: {{ .Release.Name }}-{{ .Values.webserver.volumes.name }}
                  persistentVolumeClaim:
                      claimName: {{ .Release.Name }}-{{ .Values.webserver.volumes.nameClaim }}