apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: deno-ingress
    namespace: default
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    rules:
        - host: deno.minikube
          http:
              paths:
                  - path: /
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: {{ .Values.deno.service.name }}
                            port:
                                number: {{ .Values.deno.service.port }}