apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.deno.service.name }}
  name: {{ .Values.deno.service.name }}
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.deno.service.port }}
  selector:
    app: {{ .Values.deno.service.name }}
  type: {{ .Values.deno.service.type }} 