apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.webserver.service.name }}
  namespace: default
spec:
  ports:
    - port: {{ .Values.webserver.service.port }}
      protocol: TCP
      targetPort: {{ .Values.webserver.service.targetPort }}
  selector:
    app: {{ .Values.webserver.service.name }}
  type: {{ .Values.webserver.service.type }}