apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.servicewebserver.name }}
  namespace: default
spec:
  ports:
    - port: {{ .Values.servicewebserver.port }}
      protocol: TCP
      targetPort: {{ .Values.servicewebserver.targetPort }}
  selector:
    app: {{ .Values.servicewebserver.name }}
  type: {{ .Values.servicewebserver.type }}