{{- range $pv := .Values.deno.pv}}

apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ $pv.Name }}
spec:
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: {{ $pv.PersistentVolumeReclaimPolicy }}
    storageClassName: standard
    capacity:
        storage: {{ $pv.Size }}
    hostPath:
        path: {{ $pv.PersistentVolumeReclaimPolicy }}

{{ end }}
---

{{- range $pvc := .Values.deno.pvc}}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ $pvc.Name }}
    namespace: default
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ $pvc.Size }}

{{ end }}