apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Values.webserver.pv.name }}
spec:
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: {{ .Values.webserver.pv.persistentVolumeReclaimPolicy }}
    storageClassName: standard
    capacity:
        storage: {{ .Values.webserver.pv.size }}
    hostPath:
        path: {{ .Values.webserver.pv.path }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.webserver.pvc.name }}
    namespace: default
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.webserver.pv.size }}